from django.db import models


class Category(models.IntegerChoices):
    OTHER = (0, 'Інше')
    MYSTERY = (1, 'Містика')
    THRILLER = (2, 'Трилер')
    HORROR = (3, 'Жахи')
    HISTORICAL = (4, 'Історичні романи')
    ROMANCE = (5, 'Любовні романи')
    WESTERN = (6, 'Вестерн')
    SCIENCE_FICTION = (7, 'Наукова фантастика')
    FANTASY = (8, 'Фентезі')
    MAGICAL_REALISM = (9, 'Магічний реалізм')
    NON_FICTION = (10, 'Нон-фікнш')
    REALISM = (11, 'Реалізм')
    CLASSICS = (12, 'Класика')
    POETRY = (13, 'Поезія')
    BIOGRAPHY = (14, 'Біографія')
    TEXTBOOKS = (15, 'Підручники та фахова література')
    DETECTIVE = (16, 'Детектив')
    CHILDREN = (17, 'Дитяча література')
    COMIC_BOOKS = (18, 'Комікси та графічні романи')
    ENCYCLOPEDIA = (19, 'Енциклопедії')
    DICTIONARIES = (20, 'Словники')
