# Generated by Django 4.0.6 on 2022-07-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'користувач', 'verbose_name_plural': 'користувачі'},
        ),
    ]
