# Generated by Django 4.0.6 on 2022-07-04 14:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='назва')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='автор')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=1000, verbose_name='опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ціна')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
