# Generated by Django 4.0.6 on 2022-07-04 14:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публікації'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
    ]
