# Generated by Django 4.0.6 on 2022-07-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advert_date_published_alter_advert_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'оголошення', 'verbose_name_plural': 'оголошення'},
        ),
    ]
