# Generated by Django 4.0.6 on 2022-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_remove_advert_user_advert_buyer_advert_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.IntegerField(choices=[('0', 'Інше'), ('1', 'Містика'), ('2', 'Трилер'), ('3', 'Жахи'), ('4', 'Історичні романи'), ('5', 'Любовні романи'), ('6', 'Вестерн'), ('7', 'Наукова фантастика'), ('8', 'Фентезі'), ('9', 'Магічний реалізм'), ('10', 'Нон-фікнш'), ('11', 'Реалізм'), ('12', 'Класика'), ('13', 'Поезія'), ('14', 'Біографія'), ('15', 'Підручники та фахова література'), ('16', 'Детектив'), ('17', 'Дитяча література'), ('18', 'Комікси та графічні романи'), ('19', 'Енциклопедії'), ('20', 'Словники')], default='0'),
        ),
    ]
