# Generated by Django 4.0.6 on 2022-07-04 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0008_alter_advert_category_alter_advert_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_adverts', to=settings.AUTH_USER_MODEL, verbose_name='продавець'),
        ),
    ]
